### PR TITLE
Exercises week 5 assignement and bonus

### PR DESCRIPTION
**Pull request by stjaco62**

### CODE REVIEW

**Comment by ceedee666** [comment]
We already used the Ceasar cypher in week 3s assginment. We should make sure that a new aspect is added. Is this already the case by using functions?

**Comment by ceedee666** [comment]
I persoanlly think that the bonus example is kind of lame. Prime numbers again. What about fibonacci. This would add the aspect of recursion. Another nice idee could be Pascal Trianlge (https://en.wikipedia.org/wiki/Pascal%27s_triangle). If one shades all numbers devisiable by 2,3,4 or 5 one gets nice graphics: https://en.wikipedia.org/wiki/File:Sierpinski_Pascal_triangle.svg

**Comment by stjaco62** [comment]
did we use prime numbers already? 

 

Otherwise I think it's okay (cause I really like prime numbers).

 

The other tasks always require lots of explanations.

 

Von: Christian Drumm ***@***.***> 
Gesendet: Dienstag, 29. März 2022 14:29
An: ceedee666/opensap_python_intro ***@***.***>
Cc: Jacobs, Stephan ***@***.***>; Author ***@***.***>
Betreff: Re: [ceedee666/opensap_python_intro] Exercises week 5 assignement and bonus (PR #84)

 

I persoanlly think that the bonus example is kind of lame. Prime numbers again. What about fibonacci. This would add the aspect of recursion. Another nice idee could be Pascal Trianlge (https://en.wikipedia.org/wiki/Pascal%27s_triangle). If one shades all numbers devisiable by 2,3,4 or 5 one gets nice graphics: https://en.wikipedia.org/wiki/File:Sierpinski_Pascal_triangle.svg

**Comment by stjaco62** [comment]
Wasn't aware, that Cesar was already in. Will do another assignment …

 

 

 

Von: Christian Drumm ***@***.***> 
Gesendet: Dienstag, 29. März 2022 14:23
An: ceedee666/opensap_python_intro ***@***.***>
Cc: Jacobs, Stephan ***@***.***>; Author ***@***.***>
Betreff: Re: [ceedee666/opensap_python_intro] Exercises week 5 assignement and bonus (PR #84)

 

We already used the Ceasar cypher in week 3s assginment. We should make sure that a new aspect is added. Is this already the case by using functions?

**Comment by stjaco62** [comment]
Hi,

habe jetzt den Cäsar durch einen Vignère ersetzt. Nebenbedingung sind eben die Verwendung von Fuktionen. Kann keinen Pull-Request machen, da der alte noch nicht akzeptiert ist. Jedenfalls habe ich die drei Dateien all gepushed.

 

stephan

 

Von: Jacobs, Stephan 
Gesendet: Dienstag, 29. März 2022 14:37
An: 'ceedee666/opensap_python_intro' ***@***.***>
Betreff: AW: [ceedee666/opensap_python_intro] Exercises week 5 assignement and bonus (PR #84)

 

 

Wasn't aware, that Cesar was already in. Will do another assignment …

 

 

 

Von: Christian Drumm ***@***.*** ***@***.***> > 
Gesendet: Dienstag, 29. März 2022 14:23
An: ceedee666/opensap_python_intro ***@***.*** ***@***.***> >
Cc: Jacobs, Stephan ***@***.*** ***@***.***> >; Author ***@***.*** ***@***.***> >
Betreff: Re: [ceedee666/opensap_python_intro] Exercises week 5 assignement and bonus (PR #84)

 

We already used the Ceasar cypher in week 3s assginment. We should make sure that a new aspect is added. Is this already the case by using functions?

**Pull request merged**
